---
- name: install Postfix
  apt:
    name: "{{ item }}"
  with_items:
  - postfix
  - postfix-mysql
  - postfixadmin
  - postfix-policyd-spf-python
  notify: restart postfix

- name: ensure Postfix is started and runs at startup
  service:
    name: postfix
    state: started
    enabled: yes

- name: configure Postfix (main.cf)
  template:
    src: etc/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: restart postfix

- name: configure Postfix (master.cf)
  template:
    src: etc/postfix/master.cf.j2
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: 0644
  notify: restart postfix

- name: configure Postfix (mysql_)
  template:
    src: etc/postfix/{{ item }}.j2
    dest: /etc/postfix/{{ item }}
    owner: postfix
    group: root
    mode: 0660
  with_items:
    - mysql_virtual_alias_domainaliases_maps.cf
    - mysql_virtual_alias_maps.cf
    - mysql_virtual_domains_maps.cf
    - mysql_virtual_mailbox_domainaliases_maps.cf
    - mysql_virtual_mailbox_maps.cf
  notify: restart postfix


- name: set the default domain name to be used by Postfix (/etc/mailname)
  copy:
    #content: "{{ postfix_default_domain + '\n' }}"
    content: "localhost"
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  when: postfix_default_domain is defined

- name: Create a symbolic link for postfixadmin
  file:
    src: /usr/share/postfixadmin
    dest: /var/www/postfixadmin
    owner: root
    group: root
    state: link

- name: make templates_c writeable
  file:
    path: /var/www/postfixadmin/templates_c
    owner: root
    group: www-data
    mode: '0774'

- name: configure postfixadmin (config.inc.php)
  template:
    src: etc/postfixadmin/config.inc.php.j2
    dest: /etc/postfixadmin/config.inc.php
    owner: root
    group: root
    mode: 0644
#  notify: reload nginx

- name: configure postfixadmin (dbconfig.inc.php)
  template:
    src: etc/postfixadmin/dbconfig.inc.php.j2
    dest: /etc/postfixadmin/dbconfig.inc.php
    owner: root
    group: root
    mode: 0644
#  notify: reload nginx

