# tasks file for rkhunter
---
- name: install
  apt:
    name: "rkhunter"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - rkhunter install


- name: copy default file for rkhunter
  copy:
    src: etc/default/rkhunter
    dest: /etc/default/rkhunter
    owner: root
    group: root
    mode: 0644
  tags:
    - rkhunter default


- name: cronjob file for rkhunter
  copy:
    src: etc/cron.daily/rkhunter
    dest: /etc/cron.daily/rkhunter
    owner: root
    group: root
    mode: 0755
  tags:
    - rkhunter cronjob


