---
nginx_pkgs:
  - nginx

nginx_install_epel_repo: True

nginx_official_repo: False
nginx_official_repo_mainline: False

nginx_keep_only_specified: "{{ keep_only_specified | default(False) }}"

# Whether load vars/{{ ansible_os_family }}.yml or not
nginx_load_default_vars: true

nginx_installation_type: "packages"
nginx_binary_name: "nginx"
nginx_service_name: "{{nginx_binary_name}}"
nginx_conf_dir: /etc/nginx # For this variable, a specific value for the OS can be apply in vars/{{ ansible_os_family }}.yml
#nginx_default_site_template: "site.conf.j2"

sites: [ info, webmail, kibana ]

nginx_user: nginx  # For this variable, a specific value for the OS can be apply in vars/{{ ansible_os_family }}.
nginx_group: "{{nginx_user}}"

nginx_pid_file: '/var/run/{{nginx_service_name}}.pid'

nginx_log_dir: "/var/log/nginx"
nginx_log_user: "{% if ansible_os_family == 'Debian' %}root{% else %}{{nginx_user}}{% endif %}"
nginx_log_group: "{% if ansible_os_family == 'Debian' %}adm{% else %}{{nginx_group}}{% endif %}"
nginx_log_perm: 0755
nginx_error_log_level: "error"

nginx_conf_user: root
nginx_conf_group: root
nginx_dir_perm: 0755


nginx_daemon_mode: "on"
# Set wether to start the service during the role run or keep it stopped
nginx_start_service: true
# Set wether enable Nginx service on boot or not
nginx_start_at_boot: true
