galaxy_info:
  author: Mathias BOCQUET
  description: Ansible role for postgrey, the postfix greylisting policy server.
  company: Sekoya.org

  issue_tracker_url: https://git.sekoya.org/mb/postgrey/issues

  license: GPLv3

  min_ansible_version: 1.2

  platforms:
  - name: Fedora
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all

  galaxy_tags:
    - postgrey
    - postfix
    - sysadmin

dependencies: []
