roundcube_repo: https://github.com/roundcube/roundcubemail
roundcube_version: "1.3.9"
roundcube_domain: phaah6EG.rackforest.ninja
roundcube_username_domain: phaah6EG.rackforest.ninja
roundcube_product_name: Webmail
roundcube_support_url: https://
roundcube_user: www-data
roundcube_user_shell: /bin/false
roundcube_user_home: "/usr/local/share"
roundcube_path: "/usr/local/share/roundcube"
roundcube_mysql_user: roundcube
roundcube_mysql_password: "{{ roundcube_mysql_password_enc }}"
roundcube_mysql_db: roundcubemail
roundcube_default_host: 'imaps://{{ roundcube_domain }}'
roundcube_default_port: 993
roundcube_skin: larry
roundcube_smtp_server: 'tls://{{ roundcube_domain }}'
roundcube_smtp_port: 587
roundcube_smtp_user: '%u'
roundcube_smtp_pass: '%p'
roundcube_identities_level: 1
roundcube_date_format: d.m.Y
roundcube_cipher_method: AES-256-CBC
roundcube_password_charset: UTF-8
roundcube_sendmail_delay: 4
roundcube_max_recipients: 250
roundcube_draft_autosave: 60

roundcube_plugins:
 - archive
# - carddav
# - enigma
# - getmail
 - markasjunk
# - managesieve
 - zipdownload

# list of additional configs, e.g. for plugins
roundcube_configs_extra:
  - plugins/enigma/config.inc.php

# enigma plugin settings
enigma_password_time: 1

roundcube_dependencies:
  - "{{ 'php5-intl' if ansible_distribution_major_version|int <= 8 else 'php-intl' }}"
  - "{{ 'php5-mcrypt' if ansible_distribution_major_version|int <= 8 else 'php-mcrypt' }}"
  - "{{ 'php5-mysql' if ansible_distribution_major_version|int <= 8 else 'php-mysql' }}"
  - "{{ 'php5-curl' if ansible_distribution_major_version|int <= 8 else 'php-curl' }}" # rcmcarddav
  - python-mysqldb
  - git

# carddav
roundcube_carddav_version: 3.0.3

# getmail
roundcube_getmail_repo: https://github.com/t2d/roundcube-getmail.git
