---

- name: ensure monit configs are present
  template:
    src: "monit/conf.d/{{ item }}"
    dest: "/etc/monit/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - spamassassin
  notify: restart monit
