# handlers file for fail2ban
---
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  when: service_default_state | default('started') == 'started'

- name: restart shorewall
  service:
    name: shorewall
    state: restarted

- name: restart sshd
  service:
    name: "sshd"
    state: restarted

- name: reload sysctl.conf
  command: sysctl -p
